[package]
name = "cipher-stacker-web"
version = "0.1.0"
edition = "2024"

[dependencies]
cifers = {workspace = true}
ratatui = { version = "0.30.2", default-features = false }
ratzilla = "0.3.1"
critical-section = { version = "1.2", features = ["std"] }
web-sys = { version = "0.3.81", features = [
    "Window",
    "Document",
    "Event",
    "EventTarget",
    "ClipboardEvent",
    "DataTransfer",
] }
wasm-bindgen = "0.2"

